.gitmodules, deployment/README.md, deployment/values.dev.yaml
This PR adds a development deployment of supabase to work against.
Closes #1
=> feat: Initial development deployment of supabase

docs/index.md, docs/requirements.txt, mkdocs.yml
This PR setup mkdocs with materials theme.
=> docs: Setup MkDocs documentation framework

.github/workflows/webpreview.yaml
This PR adds a web preview for the flutter web build.
=> ci: Add web preview ci with netlify

README.md, pixi.toml
Based off of yesterday's work getting this to run on my machine. Please let me know if I should be more or less verbose on any step!
=> docs: Add instructions for running the app locally

README.md, pixi.toml, src/support_sphere_py/src/support_sphere/models/public/__init__.py, src/support_sphere_py/src/support_sphere/models/public/people.py, src/support_sphere_py/src/support_sphere/models/public/user_profile.py, src/support_sphere_py/src/support_sphere/repositories/auth/user_repository.py, src/support_sphere_py/src/support_sphere/repositories/base_repository.py, src/support_sphere_py/src/support_sphere/repositories/public/__init__.py, src/support_sphere_py/src/support_sphere/repositories/public/people_repository.py, src/support_sphere_py/src/support_sphere/repositories/public/user_profile_repository.py, src/support_sphere_py/src/tests/resources/data/sample_data.csv, src/support_sphere_py/src/tests/resources/scripts/update_db_sample_data.py
Fixes #50 
- feat: add 'people' model and repository
- refactor: make repository methods static
- test: add pixi task for populating sample db entries.
=> test: add pixi task for populating sample db entries

.github/workflows/images.yaml
This PR should resolve #73 when images are copied over from dockerhub
=> ci: Setup docker image copy for supabase

.github/workflows/images.yaml
This PR updates the current version to reflect the working dev.
=> ci: Update image tag versions

.gitignore, .sops.yaml, README.md, deployment/values.cloud.yaml, pixi.lock, pixi.toml, scripts/cloud-account-setup.py, scripts/run-cloud-server.py, src/support_sphere_py/tests/resources/scripts/update_db_sample_data.py
This whole thing works now. Cloud values are encrypted with SOPS via KMS and PGP and everything.
=> build: Create values file for cloud and task for the same

.github/CODEOWNERS
Adding both niki and I as code owners for auto PR reviewers
=> chore: Add codeowners for auto PR reviewers

.vscode/launch.json, src/support_sphere/lib/constants/environment.dart, src/support_sphere/lib/utils/config.dart
This PR updates the config global variable to actually say `Config` rather than constants as this is the config for initializing supabase before build.
=> build: Add and update supabase config inputs

src/support_sphere/lib/logic/cubit/login_cubit.dart, src/support_sphere/lib/logic/cubit/login_state.dart, src/support_sphere/lib/presentation/components/auth/login_form.dart, src/support_sphere/pubspec.lock, src/support_sphere/pubspec.yaml
This PR updates the login page validators to be more robust using the collection of validators from [FormBuilderValidators](https://pub.dev/packages/form_builder_validators)
=> refactor: Update login validator to use a more robust one from community

deployment/values.cloud.yaml, pixi.lock
see: https://github.com/uw-ssec/post-disaster-comms/pull/96/files/00e14c453614c11bdce84dec2f92694c159ff140#r1777821515
=> build: Update values.cloud.yaml with realtime override present in values.dev.yaml

src/support_sphere_py/src/support_sphere/models/enums/app_roles.py, src/support_sphere_py/src/support_sphere/repositories/public/__init__.py, src/support_sphere_py/src/support_sphere/repositories/public/user_role_repository.py, src/support_sphere_py/tests/resources/scripts/update_db_sample_data.py
=> feat: update user role taxonomy and default user role

.github/workflows/cd_support_sphere_py.yml, deployment/docker/populate_db_dev.Dockerfile, pixi.toml, src/support_sphere_py/pyproject.toml
=> build: add GH action job for publishing docker image to registry

pixi.lock, src/support_sphere_py/src/support_sphere/models/public/user_profile.py, src/support_sphere_py/src/support_sphere/repositories/public/user_profile_repository.py, src/support_sphere_py/tests/resources/scripts/update_db_sample_data.py
=> refactor: remove username from user_profiles

README.md
Added the command to set the SUPABASE_URL and SUPABASE_ANON_KEY explicitly to ensure that we have a successful connection between Flutter and Supabase, and also clarified that we need to login during Supabase setup.
=> Update ReadMe with Supabase connection and login info

src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/presentation/components/icon_logo.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart, src/support_sphere/lib/presentation/router/app_body_select.dart, src/support_sphere/pubspec.lock, src/support_sphere/pubspec.yaml
This pull request introduces several changes to the `support_sphere` project, focusing on navigation, UI updates, and role-based access. The most important changes include adding role-based navigation, updating icons, and modifying the `AppPage` class to accommodate these changes.
* [`src/support_sphere/lib/constants/routes.dart`](diffhunk://#diff-cbff05c7ffb5e17adbd5bd2b934d0b73a29d29f625d413778ae7dfa43cda9d39R18-R20): Added a new method `getDestinations` to generate a list of `AppRoute` objects based on the user's role. This method includes additional routes for users with the "COM_ADMIN" role. [[1]](diffhunk://#diff-cbff05c7ffb5e17adbd5bd2b934d0b73a29d29f625d413778ae7dfa43cda9d39R18-R20) [[2]](diffhunk://#diff-cbff05c7ffb5e17adbd5bd2b934d0b73a29d29f625d413778ae7dfa43cda9d39R29-R39)
* …
=> feat: Add additional nav destinations for COM_ADMIN and use fontawesome icons

notebooks/.gitignore, pixi.lock, pixi.toml
This pull request includes updates to the `.gitignore` file and significant changes to the `pixi.toml` configuration to support a new data analysis environment, as well as minor formatting improvements.
* Added a new `data-analysis` environment with dependencies and tasks for JupyterLab and data analysis libraries. (`pixi.toml`)
* Updated the `setup-db-data-via-k8s-job` task to include a trailing comma for consistency. (`pixi.toml`)
* Improved formatting for the `setup-infra-cloud` task dependencies. (`pixi.toml`)
* Added trailing commas in various `cmd` arrays for better readability and consistency. (`pixi.toml`) [[1]](diffhunk://#diff-b092682f0ad15a352f9fa2b0a67c992454b586275ee76b74a5839ab9afdf9894L82-R99) [[2]](diffhunk://#diff-b092682f0ad15a352f9fa2b0a67c992454b586275ee76b74a5839ab9afd …
=> feat: Add data analysis framework and do some formatting

pixi.toml, src/support_sphere_py/src/support_sphere/models/public/__init__.py, src/support_sphere_py/src/support_sphere/models/public/resource.py, src/support_sphere_py/src/support_sphere/models/public/resource_cv.py, src/support_sphere_py/src/support_sphere/models/public/resource_type.py, src/support_sphere_py/tests/resources/data/resources_cv.csv, src/support_sphere_py/tests/resources/scripts/update_db_sample_data.py
This pull request introduces several changes to the `support_sphere` project, primarily focusing on adding new models and updating existing ones to enhance the resource management system. The most important changes include the addition of the `ResourceCV` model, modifications to the `Resource` and `ResourceType` models, and updates to the database sample data script to populate new resource types and controlled vocabulary.
* [`src/support_sphere_py/src/support_sphere/models/public/resource_cv.py`](diffhunk://#diff-19802de6232ebc3a97a5bb6d811d4a9c43041f36b77995baf3ddeae4075f26f9R1-R28): Added a new `ResourceCV` model to represent resource controlled vocabulary items. (`[src/support_sphere_py/src/support_sphere/models/public/resource_cv.pyR1-R28](diffhunk://#diff-19802de6232ebc3a97a5bb6d811d …
=> feat: Add resource controlled vocabulary

deployment/values.dev.yaml, src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/data/repositories/authentication.dart, src/support_sphere/lib/data/repositories/user.dart, src/support_sphere/lib/data/services/auth_service.dart, src/support_sphere/lib/data/services/user_service.dart, src/support_sphere/lib/logic/cubit/profile_cubit.dart, src/support_sphere/lib/presentation/components/profile_section.dart, src/support_sphere/lib/presentation/pages/main_app/profile/profile_body.dart, src/support_sphere/pubspec.lock, src/support_sphere/pubspec.yaml
This pull request introduces several new features and improvements to the `support_sphere` project, focusing on enhancing user management and profile handling. The most significant changes include adding new methods for updating user and household information, introducing a new `ProfileSection` component, and integrating these updates into the profile page.
* **User and Household Updates:**
* Added `updateUserPhoneNumber` method to `AuthenticationRepository` for updating user phone numbers. (`src/support_sphere/lib/data/repositories/authentication.dart`)
* Introduced methods in `UserRepository` for updating user names and household details. (`src/support_sphere/lib/data/repositories/user.dart`)
* Implemented corresponding update methods in `UserService` for updating person and household …
=> feat: Add ability to edit personal and household information on the user profile

.github/workflows/run-dev-server.yml, README.md, deployment/cloud/aws/account/main.tf, deployment/cloud/aws/infrastructure/main.tf, deployment/cloud/aws/infrastructure/modules/keys/main.tf, deployment/cloud/aws/infrastructure/modules/keys/variables.tf, deployment/cloud/aws/infrastructure/modules/ops-roles/main.tf, deployment/cloud/aws/infrastructure/modules/ops-roles/variables.tf, deployment/cloud/aws/infrastructure/variables.tf, pixi.toml, scripts/run-cloud-server.py
I do not know if this works or not and I don't have a great way to test it without it being in main
=> ci: Add a GitHub workflow to start the dev server and IAM support for GitHub OIDC

.github/workflows/run-dev-server.yml, .github/workflows/webpreview.yaml
=> ci: Hook up webpreview with cloud db values

src/support_sphere_py/src/support_sphere/scripts/resources/data/checklists.json, src/support_sphere_py/src/support_sphere/scripts/update_db_sample_data.py
Changes to JSON data:
* [`src/support_sphere_py/src/support_sphere/scripts/resources/data/checklists.json`](diffhunk://#diff-ec9b62eba8a43cc45c63e566d7d1ef0f6bf2d2b436e38b9f81e4be783ad9a282L27-R31): Added a `frequency` field to each checklist item, specifying the name and number of days for the frequency. [[1]](diffhunk://#diff-ec9b62eba8a43cc45c63e566d7d1ef0f6bf2d2b436e38b9f81e4be783ad9a282L27-R31) [[2]](diffhunk://#diff-ec9b62eba8a43cc45c63e566d7d1ef0f6bf2d2b436e38b9f81e4be783ad9a282L53-R61)
Updates to database population script:
* [`src/support_sphere_py/src/support_sphere/scripts/update_db_sample_data.py`](diffhunk://#diff-d76918361404b75d22369df86af9c8f3361a614d15f59d13e8eab845de5cafc5L13-R13): Imported the `Frequency` model and added code to populate the `Frequency` table with the …
=> feat: Add frequency sample data into setup scripts

pixi.lock, pixi.toml, src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/data/enums/resource_nav.dart, src/support_sphere/lib/data/models/user_resource.dart, src/support_sphere/lib/data/repositories/resource.dart, src/support_sphere/lib/data/services/resource_service.dart, src/support_sphere/lib/logic/cubit/manage_resource_cubit.dart, src/support_sphere/lib/logic/cubit/resource_cubit.dart, src/support_sphere/lib/logic/cubit/resource_state.dart, src/support_sphere/lib/presentation/components/container_card.dart, src/support_sphere/lib/presentation/components/manage_resource_card.dart, src/support_sphere/lib/presentation/components/resource_card.dart, src/support_sphere/lib/presentation/components/resource_search_bar.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart, src/support_sphere/lib/presentation/pages/main_app/manage_resources/add_resource_form.dart, src/support_sphere/lib/presentation/pages/main_app/manage_resources/manage_resources_body.dart, src/support_sphere/lib/presentation/pages/main_app/resource/add_to_inventory_form.dart, src/support_sphere/lib/presentation/pages/main_app/resource/request_from_inventory_form.dart, src/support_sphere/lib/presentation/pages/main_app/resource/resource_main_body.dart, src/support_sphere/lib/presentation/router/auth_select.dart
This pull request includes several changes to add new features and improve the existing functionality in the `support_sphere` project. The most important changes include adding new classes and methods to handle user resources, updating dependencies, and enhancing the user interface components.
* [`src/support_sphere/lib/data/models/user_resource.dart`](diffhunk://#diff-57f79765a092063ba51900072252b099eff6b43b1d933ccb952ea5c348ac5c0bR1-R63): Added the `UserResource` class to represent user resources, including methods for JSON serialization and copying instances.
* [`src/support_sphere/lib/data/repositories/resource.dart`](diffhunk://#diff-54d5854cf44f10ee37c97f3b817460e9664d568a3a88b18fad282929a6374feaR24-R28): Added a method `getUserResourcesByUserId` to fetch user resources by user ID. …
=> feat: Add user resources inventory view

deployment/cloud/aws/account/main.tf, deployment/cloud/aws/infrastructure/main.tf, deployment/cloud/aws/infrastructure/modules/server/main.tf, deployment/cloud/aws/infrastructure/modules/server/userdata, deployment/cloud/aws/infrastructure/modules/server/variables.tf, deployment/values.cloud.yaml, src/support_sphere/lib/utils/config.dart
=> feat: https listener

src/support_sphere/lib/data/repositories/authentication.dart, src/support_sphere/lib/data/repositories/user.dart, src/support_sphere/lib/data/services/auth_service.dart, src/support_sphere/lib/data/services/user_service.dart, src/support_sphere/lib/logic/cubit/signup_cubit.dart, src/support_sphere/test/unit_tests/auth_service_test.dart, src/support_sphere_py/src/support_sphere/scripts/execute_sql_statement.py
This pull request includes several changes to the authentication and user management processes in the `support_sphere` project. The most important changes involve modifying the signup flow to handle signup codes more robustly, including validation and invalidation of these codes, and linking users to households during signup.
* [`src/support_sphere/lib/data/repositories/authentication.dart`](diffhunk://#diff-cc74150cc24c99aef5ac413905b5c7bae49856f1fd93b8222ffa40eb6c239b82L38-R51): Updated the `signUp` method to return a map containing both the signup code validation result and the authentication response.
* [`src/support_sphere/lib/data/services/auth_service.dart`](diffhunk://#diff-28eec2ca3392e24ba46c6fb8e19cd71233c43de6bba792c24085a35fc1e20cafR2-R20): Replaced the hardcoded signup code …
=> feat: Activate signup code logic

.github/workflows/web-main.yaml, deployment/cloud/aws/infrastructure/main.tf, deployment/cloud/aws/infrastructure/modules/server/main.tf, deployment/cloud/aws/infrastructure/modules/server/userdata, deployment/cloud/aws/infrastructure/modules/server/variables.tf, deployment/values.cloud.yaml, pixi.toml
4 major changes: 
1. Parameterizes github org and repo in the userdata
2. Updates github org and repo for cloud work
3. Updates github org and repo for the run-cloud-server call within the webpreview workflow
4. Updates github org for docker images in values.cloud.yaml
=> Update gh names

.github/workflows/webpreview.yaml
I fixed the web main action earlier, not webpreview. Oops! This PR fixes the webpreview workflow
=> fix: fix webpreview

README.md, docs/index.md
This pull request includes significant updates to the `README.md` and `docs/index.md` files to reflect the rebranding of the project and to improve the documentation structure. The most important changes include renaming the project, updating the project description, and refining the documentation for local and cloud deployment.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-L184): Renamed the project from "post-disaster-comms" to "NSF Resilience App" and updated the project description to reflect its new focus on community-based peer-to-peer information and resource sharing during disasters.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-L184): Removed detailed technical setup …
=> docs: Update main documentation

docs/development-guides/1_backend_development.md
This pull request fixes a small formatting error on the backend page
=> docs: formatting fix
