UW-THINKlab/resilience

README.md, pixi.lock, pixi.toml
This PR splits pixi configuration to frontend and backend environments, this way we can quickly set things up for backend server only, so it doesn't install stuff for frontend.
Closes #31
=> build: Split pixi to frontend and backend environments

deployment/values.dev.yaml
This PR enables postgis by default for creation of Tables with geometries.
=> ci: Enable POSTGIS extension by default

src/support_sphere_py/src/support_sphere/models/enums/__init__.py, src/support_sphere_py/src/support_sphere/models/enums/app_permissions.py, src/support_sphere_py/src/support_sphere/models/enums/app_roles.py, src/support_sphere_py/src/support_sphere/models/enums/operational_status.py, src/support_sphere_py/src/support_sphere/models/public/__init__.py, src/support_sphere_py/src/support_sphere/models/public/cluster.py, src/support_sphere_py/src/support_sphere/models/public/cluster_role.py, src/support_sphere_py/src/support_sphere/models/public/role_permission.py, src/support_sphere_py/src/support_sphere/models/public/user_captain_cluster.py, src/support_sphere_py/src/support_sphere/models/public/user_profile.py, src/support_sphere_py/src/support_sphere/models/public/user_role.py, src/support_sphere_py/tests/resources/scripts/update_db_sample_data.py
=> feat: add tables user_roles, role_permissions and cluster_roles

deployment/values.dev.yaml, pixi.toml, src/support_sphere_py/src/support_sphere/__init__.py, src/support_sphere_py/src/support_sphere/models/public/__init__.py, src/support_sphere_py/src/support_sphere/models/public/cluster.py, src/support_sphere_py/src/support_sphere/models/public/operational_event.py, src/support_sphere_py/src/support_sphere/models/public/role_permission.py, src/support_sphere_py/src/support_sphere/models/public/user_profile.py, src/support_sphere_py/src/support_sphere/models/public/user_role.py, src/support_sphere_py/tests/resources/scripts/role_based_access_control.py, src/support_sphere_py/tests/resources/scripts/update_db_sample_data.py
=> feat: add role based access control for activating app emergency mode

deployment/cloud/main.tf, deployment/cloud/modules/server/main.tf, deployment/cloud/modules/server/variables.tf, deployment/cloud/variables.tf, pixi.toml
Came back to this today and remembered that we should only shutdown the server everyday in non-prod environments. Figured I'd add a new input variable, `stage`, with the currently-accepted values of `dev`, `beta`, and `prod` to help determine all of this. We'd be developing exclusively under the `dev` stage.
Feel free to tell me that this is unnecessary at this stage! Totally happy to drop this and move on :)
Providing `dev` as the `stage` envvar:
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
- destroy
OpenTofu will perform the following actions:
resource "aws_autoscaling_schedule" "scale_down" {
id                     = …
```
=> feat: Only create the scheduled action to shut down the server everyday in non-prod stages

README.md, deployment/cloud/modules/server/main.tf, pixi.lock, pixi.toml, scripts/access-cloud-server.sh
Output when there's a server running:
```
$ pixi run cloud-server-access
✨ Pixi task (cloud-server-access in deployment): scripts/access-cloud-server.sh
Sourcing credentials
Getting instance ID
Starting session with instance i-09982f5725ab6be9b
Starting session with SessionId: access-cloud-server-adpal33o3qu5pk44cfndbtweca
ssm-user@ip-10-0-101-24:~$
```
Output when there's no server running:
```
$ pixi run cloud-server-access
✨ Pixi task (cloud-server-access in deployment): scripts/access-cloud-server.sh
Sourcing credentials
Getting instance ID
No running instances found.
You can start the server by running the following command:
pixi run cloud-server-run
Then try this script again.
If you've already started a server, it can take a few minutes for it to be ready to accept connections. …
```
=> feat: Add script to access running cloud server via ssm

deployment/cloud/main.tf, deployment/cloud/variables.tf, pixi.toml
Ran into an issue where I had accidentally deleted my local `terraform.tfstate` file, which associates actual AWS resource names with their OpenTofu definitions. The `terraform.tfstate` file was in the `.gitignore` since I had misinterpreted advice given on whether or not to add these files to VCS, so I had to go in and manually rebuild associations for all 35 resources.
To avoid this, I've made the changes in this PR, which write and read the expected state files into an s3 bucket (which I'm adding definitions to create in the account setup template), which will prevent these kinds of issues in the future. More info on this can be found here: https://opentofu.org/docs/language/settings/backends/s3/
Nobody should have to rebuild that state by hand, it's very much not fun 🫠
=> build: Store OpenTofu state in S3 to enable devs on multiple machines to stay in sync

src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/logic/bloc/app_bloc.dart, src/support_sphere/lib/logic/bloc/app_event.dart, src/support_sphere/lib/logic/bloc/app_state.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart, src/support_sphere/lib/presentation/router/app_body_select.dart, src/support_sphere/lib/presentation/router/auth_select.dart
This PR closes #94. It sets up the App bloc for managing overall app state as well as getting the nav view to the various pages within the app together.
=> feat: Add app pages skeleton for navigating to other pages

deployment/values.dev.yaml, src/support_sphere/lib/data/models/operational_event.dart, src/support_sphere/lib/data/repositories/app.dart, src/support_sphere/lib/logic/bloc/app_bloc.dart, src/support_sphere/lib/logic/bloc/app_event.dart, src/support_sphere/lib/logic/bloc/app_state.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart
This PR depends on #95. It adds an additional state attribute for `AppState` called `mode`. This is meant to keep track of the `operational_status` of the app. There are 3 operational status of `emergency`, `normal`, and `test` mode. This PR relates to #27.
=> feat: Add app mode operational status logic

src/support_sphere/lib/presentation/pages/main_app/app_page.dart
This PR adds an emergency declaration button for when user is either a community admin (a.k.a `MANAGER`) for now.. and also UW team (a.k.a `ADMIN`). This PR relates to #27 
See yellow square on top right.. currently nothing happens other than printing out "Emergency button pressed" on the console
=> feat: Add emergency declaration button for com-admin and above

src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/data/models/operational_event.dart, src/support_sphere/lib/logic/bloc/app_bloc.dart, src/support_sphere/lib/logic/bloc/app_event.dart, src/support_sphere/lib/logic/bloc/app_state.dart, src/support_sphere/lib/main.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart
This PR integrates the emergency to the backend. This is part of #27. This allows user to declare emergency. 
Notice that in the back the yellow banner says that it's a test emergency. This is for the user to know it's not an actual one.
The dialog is duplicate to the test one
=> feat: Integrate emergency button with the backend

deployment/cloud/aws/account/main.tf, deployment/cloud/aws/account/terraform.tfvars, deployment/cloud/aws/account/variables.tf, deployment/cloud/aws/infrastructure/main.tf, deployment/cloud/aws/infrastructure/modules/keys/main.tf, deployment/cloud/aws/infrastructure/modules/keys/variables.tf, deployment/cloud/aws/infrastructure/modules/ops-roles/main.tf, deployment/cloud/aws/infrastructure/modules/ops-roles/variables.tf, deployment/cloud/aws/infrastructure/modules/server/main.tf, deployment/cloud/aws/infrastructure/modules/server/outputs.tf, deployment/cloud/aws/infrastructure/modules/server/userdata, deployment/cloud/aws/infrastructure/modules/server/variables.tf, deployment/cloud/aws/infrastructure/variables.tf, deployment/values.cloud.yaml, pixi.toml
Sets up ALB for the project and removes Elastic IP (since it's no longer needed). Updates relevant values in values.cloud.yaml to the LB's URL. 
Also runs a lot of annoying looking formatting stuff. Sorry about that!!!!
todo:
Proof that it has worked with the ALB's URL:
=> feat: setup ALB and DNS

src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/data/models/households.dart, src/support_sphere/lib/data/repositories/authentication.dart, src/support_sphere/lib/data/repositories/user.dart, src/support_sphere/lib/data/services/user_service.dart, src/support_sphere/lib/logic/cubit/profile_cubit.dart, src/support_sphere/lib/logic/cubit/profile_state.dart, src/support_sphere/lib/presentation/pages/main_app/profile/profile_body.dart
This PR partially satisfy #120. It contains the following changes:
=> feat: Add profile page skeleton, user, and household sections

.github/workflows/cd_support_sphere_py.yml
This PR update the fact that the CI runs for all code changes, but rather make it only for changes to python code.
=> ci: Update CI to only run on changes to the python code

src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart
This pull request includes several changes to improve code readability and maintainability by introducing constants for role and navigation route labels. The changes primarily focus on replacing hardcoded strings with defined constants and updating the related import statements.
* [`src/support_sphere/lib/constants/string_catalog.dart`](diffhunk://#diff-9663c9e5e9c15a602ae60e64b7178cbfd727abbac179b5aaefcab70a956373fdR56-R71): Added `AppRoles` and `NavRouteLabels` classes to define constants for user roles and navigation route labels.
* [`src/support_sphere/lib/constants/routes.dart`](diffhunk://#diff-cbff05c7ffb5e17adbd5bd2b934d0b73a29d29f625d413778ae7dfa43cda9d39L22-R36): Updated the `AppRoute` class to use `NavRouteLabels` constants instead of hardcoded strings for route labels.
* …
=> refactor: Make hardcoded string for routes and app roles to constants

src/support_sphere_py/src/support_sphere/scripts/update_db_sample_data.py
This pull request includes updates to the `update_db_sample_data.py` script to enhance the database population process by adding support for checklists. The changes introduce new models and a function to populate checklists from a JSON file.
* Added imports for `Checklist`, `ChecklistStep`, and `ChecklistStepsOrder` to support new checklist functionality.
* Introduced a new function `populate_checklists()` to populate checklists and their steps into the database from a JSON file.
* Updated `setup_utility_resources()` to call the new `populate_checklists()` function, ensuring checklists are included in the setup process.
Fixes #139 
This was missed! Ooops.
=> fix: Add missing checklists loader

src/support_sphere_py/src/support_sphere/scripts/update_db_sample_data.py
* Moved the `setup_utility_resources()` call to occur after `setup_user_details()`.
* Without this adjustment, calling `populate_checklists` would `trigger the insert_user_checklists_for_all_users` trigger before user data has been set up, resulting in a failure to correctly insert into the `user_checklists` table.
=> chore: Fix update_db_sample_data setup sequence

src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/data/models/checklist.dart, src/support_sphere/lib/data/models/frequency.dart, src/support_sphere/lib/data/repositories/checklist.dart, src/support_sphere/lib/data/services/checklist_service.dart, src/support_sphere/lib/logic/cubit/checklist_cubit.dart, src/support_sphere/lib/logic/cubit/checklist_state.dart, src/support_sphere/lib/presentation/components/checklist_card.dart, src/support_sphere/lib/presentation/pages/main_app/checklist/checklist_main_body.dart, src/support_sphere/pubspec.lock, src/support_sphere/pubspec.yaml
This pull request introduces a comprehensive checklist feature to the Support Sphere app, including new models, repository, service, cubit, and UI components. The changes are organized into several themes: adding new models, updating the repository and service, implementing state management with Cubit, and updating the UI.
* [`src/support_sphere/lib/data/models/checklist.dart`](diffhunk://#diff-7d28a60a377ce6079cee0c1b7095523994c05db01a769d57104fd5bf8d15a569R1-R61): Added `Checklist` and `ChecklistSteps` models to represent checklists and their steps.
* [`src/support_sphere/lib/data/models/frequency.dart`](diffhunk://#diff-a0c5862e1a466fa27c60ae510e0d1e99b60905863bb80170864bc5487c546d66R1-R16): Added `Frequency` model to represent the frequency of checklists.
* …
=> feat: Add basic user checklist main page

src/support_sphere/lib/constants/priority.dart, src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/data/repositories/checklist.dart, src/support_sphere/lib/data/services/checklist_service.dart, src/support_sphere/lib/logic/cubit/checklist_form_cubit.dart, src/support_sphere/lib/logic/cubit/checklist_form_state.dart, src/support_sphere/lib/logic/cubit/checklist_management_cubit.dart, src/support_sphere/lib/logic/cubit/checklist_management_state.dart, src/support_sphere/lib/presentation/components/checklist/checklist_step_field.dart, src/support_sphere/lib/presentation/pages/main_app/checklist/checklist_management_form_body.dart, src/support_sphere/lib/presentation/pages/main_app/checklist/checklist_management_main_body.dart, src/support_sphere_py/src/support_sphere/scripts/execute_sql_statement.py
This pull request introduces several new features and improvements to the checklist management functionality in the `support_sphere` project. The changes include adding new constants, enhancing the data repository and service layers, and implementing new cubit and UI components for checklist management.
* Added `priorityLevels` constant in `priority.dart` to define priority levels.
* Added multiple new string constants in `string_catalog.dart` for checklist management labels and messages.
* Added methods to `ChecklistRepository` for upserting checklists and steps, deleting steps, and fetching frequencies.
* Added corresponding methods in `ChecklistService` to interact with the database for the new repository methods.
* Created `ChecklistFormCubit` to manage the state and actions related …
=> feat: Add new/update preparedness checklist view

src/support_sphere/lib/constants/routes.dart, src/support_sphere/lib/presentation/pages/main_app/app_page.dart, src/support_sphere/lib/presentation/router/app_body_select.dart
This pull request includes changes to the `src/support_sphere` library to enhance the app's navigation and body selection based on screen size. The most important changes include updating the `AppNavigation` and `AppBodySelect` classes to consider screen width, and modifying the `AppPage` class to pass screen data.
Enhancements to navigation and body selection:
* [`src/support_sphere/lib/constants/routes.dart`](diffhunk://#diff-cbff05c7ffb5e17adbd5bd2b934d0b73a29d29f625d413778ae7dfa43cda9d39L20-R20): Updated `AppNavigation.getDestinations` to accept an optional `minWidth` parameter and adjusted the logic to display certain routes only for specific screen sizes. [[1]](diffhunk://#diff-cbff05c7ffb5e17adbd5bd2b934d0b73a29d29f625d413778ae7dfa43cda9d39L20-R20) …
=> feat: Add minimum screen size media query

.github/workflows/web-main.yaml
This pull request introduces a new GitHub Actions workflow for the `web` project. The workflow is triggered by pushes to the `main` branch, pull requests, and manual dispatches. It includes jobs for running a development server and deploying a preview build to GitHub Pages.
New workflow for web project:
* [`.github/workflows/web-main.yaml`](diffhunk://#diff-a3f8bd0162b14f6fb1afb8f86d38616de0c34882b62e124baedc0701aba57027R1-R53): Added a new workflow configuration that includes jobs for checking out the repository, setting up Flutter, building the web project, and deploying it to GitHub Pages.
=> build: Add build for web version and host in gh-pages

.github/workflows/web-main.yaml
This pull request includes changes to the `path` configuration in the GitHub Actions workflow file `.github/workflows/web-main.yaml`. The changes update the paths to reflect a new directory structure.
Changes in `jobs:` section:
* Updated the `path` for the "Upload Pages HTML" step to `src/support_sphere/build/web`.
* Updated the `path` for the "Upload artifact" step to `src/support_sphere/build/web/`.
=> fix: Fix path to rendered files for web

.github/workflows/web-main.yaml
This pull request includes changes to the GitHub Actions workflow configuration for the web project to enhance deployment to GitHub Pages and simplify the workflow by removing an unnecessary step.
Enhancements to deployment permissions:
* [`.github/workflows/web-main.yaml`](diffhunk://#diff-a3f8bd0162b14f6fb1afb8f86d38616de0c34882b62e124baedc0701aba57027R3-R8): Added permissions for the `GITHUB_TOKEN` to allow deployment to GitHub Pages.
Simplification of deployment steps:
* [`.github/workflows/web-main.yaml`](diffhunk://#diff-a3f8bd0162b14f6fb1afb8f86d38616de0c34882b62e124baedc0701aba57027L46-L52): Removed the step to upload the complete build folder, as it is no longer needed.
=> fix: Fix permission for web gh-pages deployment

.github/workflows/web-main.yaml
This pull request includes changes to the `jobs:` section in the `.github/workflows/web-main.yaml` file to enhance the build process for the Flutter web application. The most important changes are:
* Added the `--release` flag to the Flutter build command to ensure the application is built in release mode.
* Included the `--base-href "/post-disaster-comms/"` option to set the base URL for the web application.
=> build: Minify release web build and add base-href

src/support_sphere/lib/constants/string_catalog.dart
This pull request includes a minor change to the `src/support_sphere/lib/constants/string_catalog.dart` file. The change corrects a typo in the `allChecklist` string constant.
* [`src/support_sphere/lib/constants/string_catalog.dart`](diffhunk://#diff-9663c9e5e9c15a602ae60e64b7178cbfd727abbac179b5aaefcab70a956373fdL88-R88): Corrected the typo in the `allChecklist` string constant from 'All Checklist' to 'All Checklists'.
Fixes #210
=> chore: Fix 'All Checklists' misspelling

src/support_sphere/lib/constants/string_catalog.dart, src/support_sphere/lib/presentation/components/icon_logo.dart
This pull request includes updates to the `src/support_sphere` directory to change the app name and improve code maintainability by centralizing string constants.
Changes to app name and string constants:
* [`src/support_sphere/lib/constants/string_catalog.dart`](diffhunk://#diff-9663c9e5e9c15a602ae60e64b7178cbfd727abbac179b5aaefcab70a956373fdL3-R3): Updated the `appName` constant from 'Support Sphere' to 'Resilience - Laurelhurst'.
* [`src/support_sphere/lib/presentation/components/icon_logo.dart`](diffhunk://#diff-586a5ce69f3bf81acbd99a6e8282ff50e6c35a994e04940cfa9ec8dd69e9857dR4): Imported `string_catalog.dart` to use the centralized string constants.
* [`src/support_sphere/lib/presentation/components/icon_logo.dart`](diffhunk://#diff-586a5ce69f3bf81acbd99a6e8282ff50e6c35a994e04940cfa9e …
=> chore: Update default app name

src/support_sphere/lib/presentation/pages/main_app/profile/profile_body.dart
This pull request includes several changes to the `profile_body.dart` file in the `support_sphere` project. The changes focus on enhancing the user interface and adding new functionality to the `HouseholdInformation` class.
Enhancements to user interface and functionality:
* Added the `font_awesome_flutter` package import to the `profile_body.dart` file to use FontAwesome icons.
* Introduced a new private method `_getFullName` to concatenate the given name and family name of a `Person` object.
* Refactored the `children` widget list in the `ProfileSection` to include household members with their full names and profile icons, improving the display of household information. [[1]](diffhunk://#diff-4f8fa883208165c32b6369633dd5323a173c40e56237aad060b3115491324856L223-L282) …
=> feat: Add profile indicator for household members

README.md, docs/backend/index.md
This pull request includes a change to the `README.md` file to simplify the instructions for running the API server locally.
Documentation updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L59-L67): Removed detailed instructions for running the API server locally, including the note about running the server in editable mode and the command for production.
This was an artifact, from exploratory phase of the project. The backbone for fast api service is there, but we never actually implemented it fully.
Closes #226
=> docs: Remove fastapi instruction, not implemented

.github/workflows/web-main.yaml
This pull request includes a change to the `.github/workflows/web-main.yaml` file. The change updates the base href for the Flutter web build command.
* [`.github/workflows/web-main.yaml`](diffhunk://#diff-a3f8bd0162b14f6fb1afb8f86d38616de0c34882b62e124baedc0701aba57027L43-R43): Changed the `--base-href` parameter from `"/post-disaster-comms/"` to `"/resilience/"` in the Flutter build web command.
=> ci: Update base href for flutter gh-pages

deployment/values.dev.yaml
This pull request updates the image repository and tag for various components in the `deployment/values.dev.yaml` file. The changes ensure that the images are pulled from the new repository `ghcr.io/uw-thinklab` and use the latest tag `2024.12.23`.
Updates to image repositories and tags:
* `db:` Updated image repository to `ghcr.io/uw-thinklab/supabase-db` and tag to `2024.12.23`.
* `studio:` Updated image repository to `ghcr.io/uw-thinklab/supabase-studio` and tag to `2024.12.23`.
* `auth:` Updated image repository to `ghcr.io/uw-thinklab/supabase-auth` and tag to `2024.12.23`.
* `rest:` Updated image repository to `ghcr.io/uw-thinklab/supabase-rest` and tag to `2024.12.23`.
* `realtime:` Updated image repository to `ghcr.io/uw-thinklab/supabase-realtime` and tag to `2024.12.23`.
* …
=> chore: Update deployed images

CONTRIBUTING.md, README.md
This pull request includes updates to the contribution guidelines and references in the documentation for the Resilience App. The most important changes include the addition of a comprehensive `CONTRIBUTING.md` file and updates to the `README.md` to reference the new contributing guide.
Documentation updates:
* [`CONTRIBUTING.md`](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R1-R158): Added a detailed guide for contributing to the Resilience App, including sections on the code of conduct, reporting bugs, suggesting enhancements, making your first code contribution, and improving the documentation.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L19-R19): Updated the contributing section to refer to the …
=> docs: Add CONTRIBUTING.md file for contribution

docs/development-guides/1_backend_development.md
This pull request adds extensive documentation for backend development, detailing the components, tools, and configurations used. The most important changes include the introduction of Supabase for backend infrastructure, the use of Pixi for managing virtual environments, and the inclusion of Docker images and Helm charts for deployment.
* Added documentation on using Supabase for storage and API interfaces, along with deployment instructions using the Supabase Kubernetes Helm chart.
* Introduced Pixi for managing virtual environments and tasks, with detailed instructions on task and environment definitions in the `pixi.toml` file.
* Listed Docker images used for various services, and provided information on building and pushing these images to the GitHub Container Registry.
* Added …
=> docs: Add backend development guide

.github/workflows/cd_support_sphere_py.yml
Trying to fix the issue encountered here: https://github.com/UW-THINKlab/resilience/actions/runs/12602498317/job/35125711800 
Based on whats in here, I feel like this could work? Will revert if this experiment ends in the same failure again: https://github.com/pypa/gh-action-pypi-publish/releases/tag/v1.12.3
based on similar issue being reported here: https://github.com/pypa/gh-action-pypi-publish/issues/310
=> ci: try fixing test pypi failure by bumping version of dependent action

docs/development-guides/9_migration.md
This pull request adds a comprehensive migration guide to the `docs/development-guides/9_migration.md` file. The guide includes detailed steps for repository migrations, database URL migrations, and AWS account migrations.
Key additions include:
* **Repository Migrations**:
* Instructions for updating various code locations when changing the GitHub repository. This includes updates to `pixi.toml`, GitHub Actions configurations, deployment configurations, and `mkdocs.yml`.
* **Database URL Migration**:
* Steps for updating the deployment database URL, including reissuing the ACM certificate and updating DNS records and configuration files.
* **AWS Account Migration**:
* Detailed steps for migrating AWS accounts, including destroying old infrastructure, updating account IDs, and rebuilding …
=> docs: Add documentation for migrating various aspects of the package
